# Generated by Django 4.1.7 on 2023-04-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='done_per_cent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
