# Generated by Django 4.1.7 on 2023-04-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_project_done_per_cent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
